// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: matches.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPlayerWinsLosses = `-- name: CountPlayerWinsLosses :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN winner_id = ? THEN 1 ELSE 0 END), 0) AS INTEGER) AS wins,
    CAST(COALESCE(SUM(CASE WHEN loser_id  = ? THEN 1 ELSE 0 END), 0) AS INTEGER) AS losses
FROM matches
WHERE (winner_id = ? OR loser_id = ?) AND deleted_at IS NULL
`

type CountPlayerWinsLossesParams struct {
	WinnerID   int64 `json:"winner_id"`
	LoserID    int64 `json:"loser_id"`
	WinnerID_2 int64 `json:"winner_id_2"`
	LoserID_2  int64 `json:"loser_id_2"`
}

type CountPlayerWinsLossesRow struct {
	Wins   int64 `json:"wins"`
	Losses int64 `json:"losses"`
}

func (q *Queries) CountPlayerWinsLosses(ctx context.Context, arg CountPlayerWinsLossesParams) (CountPlayerWinsLossesRow, error) {
	row := q.db.QueryRowContext(ctx, countPlayerWinsLosses,
		arg.WinnerID,
		arg.LoserID,
		arg.WinnerID_2,
		arg.LoserID_2,
	)
	var i CountPlayerWinsLossesRow
	err := row.Scan(&i.Wins, &i.Losses)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    winner_id, loser_id, submitter_id,
    winner_rating_before, loser_rating_before,
    winner_rating_after, loser_rating_after,
    winner_delta, loser_delta,
    played_at, created_at
) VALUES (
    ?, ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?
)
RETURNING id, winner_id, loser_id, submitter_id, winner_rating_before, loser_rating_before, winner_rating_after, loser_rating_after, winner_delta, loser_delta, played_at, created_at, deleted_at, deleted_by
`

type CreateMatchParams struct {
	WinnerID           int64  `json:"winner_id"`
	LoserID            int64  `json:"loser_id"`
	SubmitterID        int64  `json:"submitter_id"`
	WinnerRatingBefore int64  `json:"winner_rating_before"`
	LoserRatingBefore  int64  `json:"loser_rating_before"`
	WinnerRatingAfter  int64  `json:"winner_rating_after"`
	LoserRatingAfter   int64  `json:"loser_rating_after"`
	WinnerDelta        int64  `json:"winner_delta"`
	LoserDelta         int64  `json:"loser_delta"`
	PlayedAt           string `json:"played_at"`
	CreatedAt          string `json:"created_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.WinnerID,
		arg.LoserID,
		arg.SubmitterID,
		arg.WinnerRatingBefore,
		arg.LoserRatingBefore,
		arg.WinnerRatingAfter,
		arg.LoserRatingAfter,
		arg.WinnerDelta,
		arg.LoserDelta,
		arg.PlayedAt,
		arg.CreatedAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WinnerID,
		&i.LoserID,
		&i.SubmitterID,
		&i.WinnerRatingBefore,
		&i.LoserRatingBefore,
		&i.WinnerRatingAfter,
		&i.LoserRatingAfter,
		&i.WinnerDelta,
		&i.LoserDelta,
		&i.PlayedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, winner_id, loser_id, submitter_id, winner_rating_before, loser_rating_before, winner_rating_after, loser_rating_after, winner_delta, loser_delta, played_at, created_at, deleted_at, deleted_by FROM matches
WHERE id = ?
`

func (q *Queries) GetMatchByID(ctx context.Context, id int64) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WinnerID,
		&i.LoserID,
		&i.SubmitterID,
		&i.WinnerRatingBefore,
		&i.LoserRatingBefore,
		&i.WinnerRatingAfter,
		&i.LoserRatingAfter,
		&i.WinnerDelta,
		&i.LoserDelta,
		&i.PlayedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPlayerHistory = `-- name: GetPlayerHistory :many
SELECT played_at, winner_id, loser_id, winner_rating_after, loser_rating_after
FROM matches
WHERE (winner_id = ? OR loser_id = ?) AND deleted_at IS NULL
ORDER BY played_at ASC, id ASC
`

type GetPlayerHistoryParams struct {
	WinnerID int64 `json:"winner_id"`
	LoserID  int64 `json:"loser_id"`
}

type GetPlayerHistoryRow struct {
	PlayedAt          string `json:"played_at"`
	WinnerID          int64  `json:"winner_id"`
	LoserID           int64  `json:"loser_id"`
	WinnerRatingAfter int64  `json:"winner_rating_after"`
	LoserRatingAfter  int64  `json:"loser_rating_after"`
}

func (q *Queries) GetPlayerHistory(ctx context.Context, arg GetPlayerHistoryParams) ([]GetPlayerHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerHistory, arg.WinnerID, arg.LoserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerHistoryRow{}
	for rows.Next() {
		var i GetPlayerHistoryRow
		if err := rows.Scan(
			&i.PlayedAt,
			&i.WinnerID,
			&i.LoserID,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedMatches = `-- name: ListDeletedMatches :many
SELECT id, winner_id, loser_id, submitter_id, winner_rating_before, loser_rating_before, winner_rating_after, loser_rating_after, winner_delta, loser_delta, played_at, created_at, deleted_at, deleted_by FROM matches
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.WinnerID,
			&i.LoserID,
			&i.SubmitterID,
			&i.WinnerRatingBefore,
			&i.LoserRatingBefore,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
			&i.WinnerDelta,
			&i.LoserDelta,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalMatches = `-- name: ListGlobalMatches :many
SELECT id, winner_id, loser_id, submitter_id, winner_rating_before, loser_rating_before, winner_rating_after, loser_rating_after, winner_delta, loser_delta, played_at, created_at, deleted_at, deleted_by FROM matches
WHERE deleted_at IS NULL
ORDER BY played_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListGlobalMatchesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListGlobalMatches(ctx context.Context, arg ListGlobalMatchesParams) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.WinnerID,
			&i.LoserID,
			&i.SubmitterID,
			&i.WinnerRatingBefore,
			&i.LoserRatingBefore,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
			&i.WinnerDelta,
			&i.LoserDelta,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerMatches = `-- name: ListPlayerMatches :many
SELECT id, winner_id, loser_id, submitter_id, winner_rating_before, loser_rating_before, winner_rating_after, loser_rating_after, winner_delta, loser_delta, played_at, created_at, deleted_at, deleted_by FROM matches
WHERE (winner_id = ? OR loser_id = ?) AND deleted_at IS NULL
ORDER BY played_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPlayerMatchesParams struct {
	WinnerID int64 `json:"winner_id"`
	LoserID  int64 `json:"loser_id"`
	Limit    int64 `json:"limit"`
	Offset   int64 `json:"offset"`
}

func (q *Queries) ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerMatches,
		arg.WinnerID,
		arg.LoserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.WinnerID,
			&i.LoserID,
			&i.SubmitterID,
			&i.WinnerRatingBefore,
			&i.LoserRatingBefore,
			&i.WinnerRatingAfter,
			&i.LoserRatingAfter,
			&i.WinnerDelta,
			&i.LoserDelta,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreMatch = `-- name: RestoreMatch :exec
UPDATE matches
SET deleted_at = NULL, deleted_by = NULL
WHERE id = ?
`

func (q *Queries) RestoreMatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreMatch, id)
	return err
}

const softDeleteMatch = `-- name: SoftDeleteMatch :exec
UPDATE matches
SET deleted_at = ?, deleted_by = ?
WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteMatchParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	DeletedBy sql.NullInt64  `json:"deleted_by"`
	ID        int64          `json:"id"`
}

func (q *Queries) SoftDeleteMatch(ctx context.Context, arg SoftDeleteMatchParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteMatch, arg.DeletedAt, arg.DeletedBy, arg.ID)
	return err
}
