// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type AdminSession struct {
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Match struct {
	ID                 int64          `json:"id"`
	WinnerID           int64          `json:"winner_id"`
	LoserID            int64          `json:"loser_id"`
	SubmitterID        int64          `json:"submitter_id"`
	WinnerRatingBefore float64        `json:"winner_rating_before"`
	LoserRatingBefore  float64        `json:"loser_rating_before"`
	WinnerRatingAfter  float64        `json:"winner_rating_after"`
	LoserRatingAfter   float64        `json:"loser_rating_after"`
	WinnerDelta        float64        `json:"winner_delta"`
	LoserDelta         float64        `json:"loser_delta"`
	PlayedAt           string         `json:"played_at"`
	CreatedAt          string         `json:"created_at"`
	DeletedAt          sql.NullString `json:"deleted_at"`
	DeletedBy          sql.NullInt64  `json:"deleted_by"`
}

type Player struct {
	ID        int64   `json:"id"`
	Username  string  `json:"username"`
	Rating    float64 `json:"rating"`
	CreatedAt string  `json:"created_at"`
}

type Session struct {
	Token     string `json:"token"`
	PlayerID  int64  `json:"player_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
