// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: players.sql

package sqlc

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (username, rating)
VALUES (?, ?)
RETURNING id, username, rating, created_at
`

type CreatePlayerParams struct {
	Username string `json:"username"`
	Rating   int64  `json:"rating"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Username, arg.Rating)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, username, rating, created_at FROM players
WHERE id = ?
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, rating, created_at FROM players
WHERE username = ?
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayersByRating = `-- name: ListPlayersByRating :many
SELECT id, username, rating, created_at FROM players
ORDER BY rating DESC, id ASC
`

func (q *Queries) ListPlayersByRating(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersByRating)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerRating = `-- name: UpdatePlayerRating :exec
UPDATE players
SET rating = ?
WHERE id = ?
`

type UpdatePlayerRatingParams struct {
	Rating int64 `json:"rating"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerRating, arg.Rating, arg.ID)
	return err
}
