// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	// All four ? placeholders must be the SAME player_id (wins-filter, losses-filter, then the two WHERE-clause checks).
	CountPlayerWinsLosses(ctx context.Context, arg CountPlayerWinsLossesParams) (CountPlayerWinsLossesRow, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteAdminSession(ctx context.Context, token string) error
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteSession(ctx context.Context, token string) error
	GetAdminSession(ctx context.Context, token string) (AdminSession, error)
	GetMatchByID(ctx context.Context, id int64) (Match, error)
	GetPlayerByID(ctx context.Context, id int64) (Player, error)
	GetPlayerByUsername(ctx context.Context, username string) (Player, error)
	GetPlayerHistory(ctx context.Context, arg GetPlayerHistoryParams) ([]GetPlayerHistoryRow, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetSetting(ctx context.Context, key string) (string, error)
	ListDeletedMatches(ctx context.Context) ([]Match, error)
	ListGlobalMatches(ctx context.Context, arg ListGlobalMatchesParams) ([]Match, error)
	ListPlayerMatches(ctx context.Context, arg ListPlayerMatchesParams) ([]Match, error)
	ListPlayersByRating(ctx context.Context) ([]Player, error)
	RestoreMatch(ctx context.Context, id int64) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	SoftDeleteMatch(ctx context.Context, arg SoftDeleteMatchParams) error
	UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) error
}

var _ Querier = (*Queries)(nil)
