// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions (token, created_at, expires_at)
VALUES (?, ?, ?)
`

type CreateAdminSessionParams struct {
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdminSession, arg.Token, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, player_id, created_at, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string `json:"token"`
	PlayerID  int64  `json:"player_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Token,
		arg.PlayerID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAdminSession = `-- name: DeleteAdminSession :exec
DELETE FROM admin_sessions
WHERE token = ?
`

func (q *Queries) DeleteAdminSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSession, token)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT token, created_at, expires_at FROM admin_sessions
WHERE token = ?
`

func (q *Queries) GetAdminSession(ctx context.Context, token string) (AdminSession, error) {
	row := q.db.QueryRowContext(ctx, getAdminSession, token)
	var i AdminSession
	err := row.Scan(&i.Token, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, player_id, created_at, expires_at FROM sessions
WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.PlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
